# Config file for [Air](https://github.com/air-verse/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main.exe ."
bin = "tmp/main.exe"
# args_bin = ["-env", ".env.local"]
include_ext = ["go"]
exclude_dir = ["tmp", "ui"]
exclude_unchanged = true
follow_symlink = true

log = "air.log"

poll = true
poll_interval = 500 # ms
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 500 # ms

# Stop running old binary when build errors occur.
stop_on_error = true

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true


[log]
# Show log time
time = false
# Only show main log (silences watcher, build, runner)
main_only = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
